version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: company-api

    working_dir: /var/www

    volumes:
      - ./:/var/www

    ports:
      - "8000:8000"

    depends_on:
      mysql:
        condition: service_healthy

    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.4

    container_name: company-db

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: company
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: company
      MYSQL_PASSWORD: company

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data: